TEST_FASTQS = [
    "Mycolicibacterium_smegmatis/test1_1.fastq.gz",
    "Mycolicibacterium_smegmatis/test1_2.fastq.gz",
    "Mycolicibacterium_smegmatis/test2_1.fastq.gz",
    "Mycolicibacterium_smegmatis/test2_2.fastq.gz",
    "Mycolicibacterium_smegmatis/test3_1.fastq.gz",
    "Mycolicibacterium_smegmatis/test3_2.fastq.gz",
    "Mycolicibacterium_smegmatis/test4_1.fastq.gz",
    "Mycolicibacterium_smegmatis/test4_2.fastq.gz",
    "Mycolicibacterium_smegmatis/test5_1.fastq.gz",
    "Mycolicibacterium_smegmatis/test5_2.fastq.gz",
    "Mycolicibacterium_smegmatis/test6_1.fastq.gz",
    "Mycolicibacterium_smegmatis/test6_2.fastq.gz",
    "Mycolicibacterium_smegmatis/test7.fastq.gz",
    "Mycolicibacterium_smegmatis/test8.fastq.gz",
]

TEST_REFERENCE_FILES = [
    "Mycolicibacterium_smegmatis/Mycolicibacterium_smegmatis.gff",
    "Mycolicibacterium_smegmatis/Mycolicibacterium_smegmatis.fa",
]

CURL = "curl --fail --location --retry 3 --retry-delay 5 --retry-connrefused"


rule all:
    input:
        TEST_REFERENCE_FILES,
        TEST_FASTQS,
        "Mycolicibacterium_smegmatis/test.md5.done"

rule get_test_samples:
    input: 
    output:
        r1="Mycolicibacterium_smegmatis/test1_1.fastq.gz",
        r2="Mycolicibacterium_smegmatis/test1_2.fastq.gz",
        r3="Mycolicibacterium_smegmatis/test2_1.fastq.gz",
        r4="Mycolicibacterium_smegmatis/test2_2.fastq.gz",
        r5="Mycolicibacterium_smegmatis/test3_1.fastq.gz",
        r6="Mycolicibacterium_smegmatis/test3_2.fastq.gz",
        r7="Mycolicibacterium_smegmatis/test4_1.fastq.gz",
        r8="Mycolicibacterium_smegmatis/test4_2.fastq.gz",
        r9="Mycolicibacterium_smegmatis/test5_1.fastq.gz",
        r10="Mycolicibacterium_smegmatis/test5_2.fastq.gz",
        r11="Mycolicibacterium_smegmatis/test6_1.fastq.gz",
        r12="Mycolicibacterium_smegmatis/test6_2.fastq.gz",
        r13="Mycolicibacterium_smegmatis/test7.fastq.gz",
        r14="Mycolicibacterium_smegmatis/test8.fastq.gz"
    shell: 
        """
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/032/SRR23849832/SRR23849832_1.fastq.gz -o {output.r1}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/032/SRR23849832/SRR23849832_2.fastq.gz -o {output.r2}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/031/SRR23849831/SRR23849831_1.fastq.gz -o {output.r3}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/031/SRR23849831/SRR23849831_2.fastq.gz -o {output.r4}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/017/SRR23849817/SRR23849817_1.fastq.gz -o {output.r5}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/017/SRR23849817/SRR23849817_2.fastq.gz -o {output.r6}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/015/SRR23849815/SRR23849815_1.fastq.gz -o {output.r7}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/015/SRR23849815/SRR23849815_2.fastq.gz -o {output.r8}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/014/SRR23849814/SRR23849814_1.fastq.gz -o {output.r9}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/014/SRR23849814/SRR23849814_2.fastq.gz -o {output.r10}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/013/SRR23849813/SRR23849813_1.fastq.gz -o {output.r11}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR238/013/SRR23849813/SRR23849813_2.fastq.gz -o {output.r12}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR147/042/SRR14743442/SRR14743442.fastq.gz -o {output.r13}
        {CURL} https://ftp.sra.ebi.ac.uk/vol1/fastq/SRR147/041/SRR14743441/SRR14743441.fastq.gz -o {output.r14}
        """

rule get_genome:
    input: 
    output: "Mycolicibacterium_smegmatis/Mycolicibacterium_smegmatis.fa"
    shell: 
        """
        {CURL} https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/013/349/145/GCF_013349145.1_ASM1334914v1/GCF_013349145.1_ASM1334914v1_genomic.fna.gz | gunzip > {output}
        """

rule get_gff3:
    input: 
    output: "Mycolicibacterium_smegmatis/Mycolicibacterium_smegmatis.gff"
    shell: 
        """
        {CURL} https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/013/349/145/GCF_013349145.1_ASM1334914v1/GCF_013349145.1_ASM1334914v1_genomic.gff.gz | gunzip > {output}
        """

rule md5checksum:
    input:
        TEST_REFERENCE_FILES,
        TEST_FASTQS,
        md5="Mycolicibacterium_smegmatis/test.md5",
    output: "Mycolicibacterium_smegmatis/test.md5.done"
    conda: "test.yml"
    shell: 
        """
        rhash --check Mycolicibacterium_smegmatis/test.md5 && touch {output}
        """
