"""Create an RNASeq pipeline up to the start of defrential analysis."""

from snakemake.utils import min_version
from scripts.utils import *

min_version("6.0")  # Enforces minimum conda version ~


configfile: "config/config.json"
configfile: "config/tools.json"


pepfile: config["pepfile"]


validate_preflight_inputs(pep, config)


include: "rules/utilities.smk"
include: "rules/resources.smk"
include: "rules/trimming.smk"
include: "rules/quantification.smk"
include: "rules/metrics.smk"
include: "rules/deseq.smk"


rule all:
    input:
        expand(
            rules.deseq2.output[0], project=pep.sample_table.project.unique().tolist()
        ),
        expand(
            rules.qc_summary.output[0],
            project=pep.sample_table.project.unique().tolist(),
        ),
