pep_version: 2.0.0
sample_table: "../test/test_samples.csv" #Change for run
subsample_table: "../test/test_subsamples.csv" #Change for run
sample_modifiers:
  append:
    raw_data: "test/Mycolicibacterium_smegmatis/" #Change for run
  duplicate:
    sample_type: reads
  derive:
    attributes: [reads]
    sources:
      rna: "{raw_data}/{subsample}*.fastq.gz"