pep_version: 2.0.0
sample_table: "../test/r_peoriensis_samples.csv" #Change for run
subsample_table: "../test/r_peoriensis_subsamples.csv" #Change for run
sample_modifiers:
  append:
    raw_data: "/Users/kananen/Documents/workspace/bradley_lab/christian/R_peoriensis/" #Change for run
  duplicate:
    sample_type: reads
  derive:
    attributes: [reads]
    sources:
      rna: "{raw_data}/{subsample}*.fastq.gz"