description: RNAseq schema that allows for bacterial paired end read quantification. 
imports:
  - http:/schema.databio.org/pep/2.0.0.yaml
properties:
  samples:
    type: array
    items:
      type: object
      properties:
        project:
          type: string
          description: "Project Identifier For The Sample"
        sample_name: 
          type: string
          description: "Name Of The Sample"
        seq_method:
          type: string
          description: "Paired end only, no support for other types"
          enum: ["paired_end"]
        reads:
          anyOf:
            - type: string
              description: "Fastq files for a sample"
            - type: array
              items:
              type: string
      required_files:
        - reads
      required:
        - sample_name
        - project
        - organism
        - seq_method
required:
  - samples